### PR TITLE
Host TBB bundles on Github Releases

### PR DESCRIPTION
**Pull request by DonnchaC**
This updates the `upload/bundles2github.py` script to host Tor Browser bundles on Github releases rather than committing the files into a massive git repo.

The user experience could be improved by pushing as updated `README.md` for the `TheTorProject/gettorbrowser` repo which links to the latest bundle in different languages. If this repo was spread and indexed in Google this would be a good censorship resistant way of getting Tor without even having to email GetTor.

Ideas for how to improve the user experience are welcome. One current issue is that the releases page shows meaningless links to 'Source Code' archives. We should look to see if these links can be disabled.

### CODE REVIEW

**Comment by ilv** [comment]
Thanks @DonnchaC! Using releases instead of committing the files seems like a good option. I have checked other repos with releases and all seem to have the "Source Code" (zip and tar.gz) files that you mention. From what I understand, the changes to bundles2github add a new zip file for each of the bundles, in addition to Source Code, right?

Having an updated README (or landing page) with the links would certainly be of help, and it could help to avoid people from downloading the useless "Source Code" files (I will open a new ticket to discuss that).

I will also check if github3 module is available to use on getulum (or see if I can install it). Merging this changes will depend on that.

**Comment by ilv** [comment]
@DonnchaC github3 is not available on getulum for installing it system-wide and I couldn't install it locally either (for the user in the server). However, the current script uses libsaas, which [also have support](http://docs.libsaas.net/en/latest/generated/github/) for releases. What do you think of rewriting your changes to use libsaas? 

p.s.: there is also a Downloads resource, maybe we can avoid the "Source Code" thing with that? (I haven't tried it, I'm just thinking out loud).

**Comment by DonnchaC** [comment]
Sure! Let me check if I can port this to use the `libsaas` library. I changed to `github3` as I was having some trouble with `libsaas`'s GitHub API.

**Comment by DonnchaC** [comment]
I've filled a ticket asking the `libsaas` people to make a new release (https://github.com/ducksboard/libsaas/issues/94). However that project looks dead, the company who created `libsaas` have been acquired by someone else.

The `github3.py` module should meet our requirements for creating commits and releases. Can we get this installed on the box where gettor runs?

**Comment by ilv** [comment]
Unfortunately we can't get github3.py installed on getulum (the box where gettor runs). The system does not have github3 available for installing it via apt and pip is not available. When trying to install it locally it fails on uritemplate dependency.

**Comment by ilv** [comment]
Just for the record, with the help of @DonnchaC I could finally install github3 on the gettor box. So, changes look good to me. Thanks!

**Pull request merged**
