### PR TITLE
Arabic

### PR DESCRIPTION
**Pull request by agharbeia**
A proposed Arabic translation for the messages for SMTP and XMPP. Twitter seems to be unimplemented yet?

### CODE REVIEW

**Comment by ilv** [comment]
Thanks! I'll see if I can find someone that can review this.

**Comment by mrphs** [comment]
I bet Localization Lab can help us with this. You probably wanna see who
is the coordinator of translation at Tor. They must work with each
other. I'm happy to introduce you to them if that route didn't work out.

**Comment by ilv** [comment]
This was successfully reviewed. Thanks @agharbeia!

**Comment by agharbeia** [comment]
@ilv, it's good to do something for Tor. It's been ten years since I first translated Vidalia.

**Pull request merged**
